name: linter

on: [push]

jobs:
  lint:
    name: run golint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.x'
      - name: check out code
        uses: actions/checkout@v2
      - name: install golint
        run: go install golang.org/x/lint/golint@latest
      - name: run golint
        run: golint ./...
