name: golint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Run Golint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18' # Adjust as per your Go version
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install golint
        run: go install golang.org/x/lint/golint@latest
      - name: Run golint
        run: golint ./...
