name: tests

on: [push]

jobs:
  test:
    name: run go test
    runs-on: ubuntu-latest
    steps:
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
      - name: check out code
        uses: actions/checkout@v2
      - name: test
        run: go test ./... -v